### ISSUE TITLE
Tasks required nativescript-schematics v1 release

### ISSUE THREAD

**Issue by sebawita** [NativeScript/nativescript-schematics#11]
## Core tasks required for the release
 * [x] - create a migration schematic `add-ns` - Angular web => Angular shared
   * [x] - expose web => shared through `ng add @nativescript/schematics`
   * [x] - make migration work with Angular 6
     * [x] - initial implementation
     * [ ] - add tests: #63
 * [x] - create ng new schematic:
   * [x] - create a NativeScript only project: `ng new --collection=@nativescript/schematics app-name`
   * [x] - create a code sharing project project: `ng new --collection=@nativescript/schematics app-name --shared`
 * [x] - Update `nativescript-dev-webpack`
   * [x] - to work with Webpack v4
   * [x] - to allow `tns run ios/android --bundle` to pick `.tns` files as NativeScript specific files
   * [x] - need to release an official version of the plugin
 * [x] - add generate schematics for NativeScript
   * [x] - update `ng generate component` and `ng generate module` to work with NativeScript
     * [x] - to work in a NativeScript only project
     * [x] - to work in a code sharing structure with Angular 6
  * [x] - create an updated version of a code sharing project seed working with Angular 6
 * [x] - create documentation for code-sharing

## Additional tasks
 * [x] - Test builds with Angular v6
 * [x] - Refactor ng new templates

## Deprecated
This schematics will no longer support `@angular/cli` 1.x or `@angular` before 6.x.

**Comment by sebawita** [comment]
## Core tasks required for the release
 * [x] - create a migration schematic `add-ns` - Angular web => Angular shared
   * [x] - expose web => shared through `ng add @nativescript/schematics`
   * [x] - make migration work with Angular 6
     * [x] - initial implementation
     * [ ] - need tests to verify it works
 * [ ] - create a migration schematic `add-web` - Angular NativeScript => Angular shared
   * [ ] - update it to work with Angular v6
 * [x] - Update `nativescript-dev-webpack`
   * [x] - to work with Webpack v4
   * [x] - to allow `tns run ios/android --bundle` to pick `.tns` files as NativeScript specific files
   * [ ] - need to release an official version of the plugin
 * [x] - add generate schematics for NativeScript
   * [x] - update `ng generate component` and `ng generate module` to work with NativeScript
     * [x] - to work in a NativeScript only project
     * [x] - to work in a code sharing structure with Angular 6
  * [x] - create an updated version of a code sharing project seed working with Angular 6
 * [ ] - create documentation for migration: 
   * [ ] - tutorial outlining the migration process
   * [ ] - tutorial outlining development process in a code sharing project
   * [ ] - each command and its parameters
     * [ ] - `add-ns` / `ng add @nativescript/schematics`
     * [ ] - `add-web`
     * [ ] - `migrate-component`
     * [ ] - `migrate-module`
 * [ ] - create documentation for `ng generate` for NativeScript

## Additional tasks
 * [ ] - Example projects – showing before, after and steps to get there
 * [ ] - Testing the schematics against existing Angular Web projects. Our current schematics cover mostly basic scenarios, this is to ensure we can also cover more advanced scenarios.
 * [ ] - Need some time to test builds with Angular v6 – I should be able to start next week, once Mira completes the task around .tns extensions.

## Deprecated
This schematics will no longer support `@angular/cli` 1.x or `@angular` before 6.x.

**Comment by zxlee618** [comment]
any ETA on the release? 😄

**Comment by sebawita** [comment]
Hi @zxlee618,
The project is now live and ready to use.
We are still working on new stuff, but the solution should work for most cases.
The only caveat is that currently we are using `@angular/cli@6.1.0-beta.0`. As soon as the next `rc` comes out or the full version, we will migrate the schematics to `@angular/cli@6.1.0`

**Comment by zxlee618** [comment]
@sebawita Awesome! thanks 👍

**Comment by sebawita** [comment]
## Core tasks required for the release
 * [x] - create a migration schematic `add-ns` - Angular web => Angular shared
   * [x] - expose web => shared through `ng add @nativescript/schematics`
   * [x] - make migration work with Angular 6
     * [x] - initial implementation
     * [ ] - add tests
 * [x] - create ng new schematic:
   * [x] - create a NativeScript only project: `ng new --collection=@nativescript/schematics app-name`
   * [x] - create a code sharing project project: `ng new --collection=@nativescript/schematics app-name --shared`
 * [x] - Update `nativescript-dev-webpack`
   * [x] - to work with Webpack v4
   * [x] - to allow `tns run ios/android --bundle` to pick `.tns` files as NativeScript specific files
   * [x] - need to release an official version of the plugin
 * [x] - add generate schematics for NativeScript
   * [x] - update `ng generate component` and `ng generate module` to work with NativeScript
     * [x] - to work in a NativeScript only project
     * [x] - to work in a code sharing structure with Angular 6
  * [x] - create an updated version of a code sharing project seed working with Angular 6
 * [ ] - create documentation for migration: 
   * [ ] - tutorial outlining the migration process
   * [ ] - tutorial outlining development process in a code sharing project
   * [ ] - each command and its parameters
     * [ ] - `add-ns` / `ng add @nativescript/schematics`
     * [ ] - `add-web`
     * [ ] - `migrate-component`
     * [ ] - `migrate-module`
 * [ ] - create documentation for `ng generate` for NativeScript

## Additional tasks
 * [ ] - Example projects – showing before, after and steps to get there
 * [ ] - Testing the schematics against existing Angular Web projects. Our current schematics cover mostly basic scenarios, this is to ensure we can also cover more advanced scenarios.
 * [ ] - Need some time to test builds with Angular v6
 * [ ] - create a migration schematic `add-web` - Angular NativeScript => Angular shared
   * [ ] - update it to work with Angular v6
 * [ ] - Refactor ng new templates

## Deprecated
This schematics will no longer support `@angular/cli` 1.x or `@angular` before 6.x.

**Comment by ChiKaLiO** [comment]
someoine help me lol ! 
Schematic "add-web" not found in collection "@schematics/angular".
Error: Schematic "add-web" not found in collection "@schematics/angular"
