### ISSUE TITLE
tns build does not support Angular 6 sub projects

### ISSUE THREAD

**Issue by ovirta** [NativeScript/nativescript-schematics#119]
Paste from Nativecript forum question:
"
We have relatively large web-app built with Angular 6 and we have few sub projects added to the main project. They are created with ng g application

Does tns toolset support building these Angular 6 sub projects to Android / iOS?

Example commands:
ng g application mynsapp
ng add --project mynsapp @nativescript/schematics
tns build android --bundle --project mynsapp

The last command fails currently.

tns version: 4.2.3
Angular CLI: 6.2.1
Node: 8.11.3
OS: win32 x64
Angular: 6.1.7
"

https://discourse.nativescript.org/t/does-tns-build-support-angular-6-sub-projects/8206/2

**Comment by sebawita** [comment]
Hi @ovirta,
Currently we are not covering this scenario.
I will investigate it.
This shouldn't be too hard to implement.
Thanks,
Sebastian

**Comment by kl4n4** [comment]
I could also really use sub project support for native script projects/schematics. If you already have an update on whether it would be a simple adaption or not please let me know. Thanks!

**Comment by sis0k0** [comment]
closing in favor of #25
