### ISSUE TITLE
Custom font not applied in iOS

### ISSUE THREAD

**Issue by overwise** [NativeScript/nativescript-schematics#125]
I'm working on Web + Mobile Code Sharing project and I'm trying to apply Roboto Regular font, but it seems it's not working in iOS. I've seen that there are tons of questions about iOS and custom fonts out there, but none of given answers solves my problem, so I wanted to check if it maybe has something to do with nativescript-schematics.
I manage to use this font for Android and Angular web app, but it fails in iOS.

Font file location:`src/app/fonts/Roboto-Regular.ttf`

src/_app-common.scss
`.roboto {
  font-family: 'Roboto-Regular',  'Roboto Regular';
}`

src/app/pages/my/my.component.tns.html
`<Label [nsRouterLink]="['/about']" text="About" class="h1 text-center roboto" textWrap="true"></Label>`

package.json
```json
{
      "name": "appname",
      "nativescript": {
        "id": "no.app.id",
        "tns-android": {
          "version": "4.2.0"
        },
        "tns-ios": {
          "version": "4.2.0"
        }
      },
      "version": "0.0.0",
      "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "android": "tns run android --bundle",
        "ios": "tns run ios --bundle"
      },
      "private": true,
      "dependencies": {
        "@angular/animations": "~6.1.0",
        "@angular/common": "~6.1.0",
        "@angular/compiler": "~6.1.0",
        "@angular/core": "~6.1.0",
        "@angular/forms": "~6.1.0",
        "@angular/http": "~6.1.0",
        "@angular/platform-browser": "~6.1.0",
        "@angular/platform-browser-dynamic": "~6.1.0",
        "@angular/router": "~6.1.0",
        "core-js": "^2.5.4",
        "nativescript-angular": "~6.1.0",
        "nativescript-theme-core": "~1.0.4",
        "normalize.css": "^8.0.0",
        "reflect-metadata": "~0.1.8",
        "rxjs": "^6.0.0",
        "tns-core-modules": "~4.2.0",
        "zone.js": "^0.8.26"
      },
      "devDependencies": {
        "@angular/cli": "^6.2.0",
        "@angular/compiler-cli": "~6.0.3",
        "@angular-devkit/build-angular": "^0.8.0",
        "@nativescript/schematics": "~0.3.0",
        "@types/jasmine": "~2.8.6",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "~8.9.4",
        "codelyzer": "~4.2.1",
        "jasmine-core": "~2.99.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~1.7.1",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.0",
        "karma-jasmine": "~1.1.1",
        "karma-jasmine-html-reporter": "^0.2.2",
        "nativescript-dev-typescript": "~0.7.0",
        "nativescript-dev-webpack": "^0.16.0",
        "protractor": "~5.3.0",
        "ts-node": "~5.0.1",
        "tslint": "~5.9.1",
        "typescript": "~2.7.2",
        "nativescript-dev-sass": "~1.6.0"
      }
    }
```

Thanks

**Comment by overwise** [comment]
Just an update: Placing custom fonts in `src/fonts/` instead of `src/app/fonts/` worked for iOS. Yet to test if Android is going to pick them up.

**Comment by sis0k0** [comment]
Hi @overwise, did you verify that the above solution works for Android, too?

**Comment by overwise** [comment]
@sis0k0 Yes, it worked for both iOS and Android.

**Comment by sis0k0** [comment]
Great! By default, webpack is configured to copy the `src/fonts` directory to your built project. That's why it doesn't work if the fonts are nested in `src/app/fonts`. You can modify that behavior from the `webpack.config.js` file in your project:
https://github.com/NativeScript/nativescript-dev-webpack/blob/2470d3bd5de6c18a97eb7b5b1c701989eff68eb4/templates/webpack.angular.js#L224-L228

**Comment by Nahiduzzaman** [comment]
I put fonts folder inside src folder.

When i preparing build using Xcode for publishing IOS, I got error right after launch screen 'You don’t have permission to save the file “fonts” in the folder <APP_NAME>.

createDirectoryAtPathWithIntermediateDirectoriesAttributesError([native code])

Anyone get this error?
