### ISSUE TITLE
application entry point file not found

### ISSUE THREAD

**Issue by lschaffer** [NativeScript/nativescript-schematics#13]
Scenario

npm i -g @angular/cli  --> 6.0.3
npm i -g @nativescript/schematics  -> 0.1,0 (latest)

ng new testapp
ng add @nativescript/schematics --- a complete test app (barcelona) has been generated web version is working
tns run android  --> app is compiling, installing into the device then come this error

**:application entry point file not found Please specify in package.json**

What is missing ?

---Updated 

tns was 4.0.1 
I have updated to 4.1
Project has been rectrated - schematics added - tns updated 
Then tns debug android 
After a while a lot of error message

_platforms/android/app/src/main/assets/app/tns_modules/@schematics/angular/service/files/__name@dasherize@if-flat__/__name@dasherize__.service.spec.ts(12,96): error TS1109: Expression expected.
platforms/android/app/src/main/assets/app/tns_modules/@schematics/angular/service/files/__name@dasherize@if-flat__/__name@dasherize__.service.spec.ts(12,106): error TS1005: ',' expected.
platforms/android/app/src/main/assets/app/tns_modules/@schematics/angular/service/files/__name@dasherize@if-flat__/__name@dasherize__.service.spec.ts(13,20): error TS1005: '{' expected.
platforms/android/app/src/main/assets/app/tns_modules/@schematics/angular/service/files/__name@dasherize@if-flat__/__name@dasherize__.service.spec.ts(14,5): error TS1005: ';' expected.
platforms/android/app/src/main/assets/app/tns_modules/@schematics/angular/service/files/__name@dasherize@if-flat__/__name@dasherize__.service.spec.ts(15,1): error TS1128: Declaration or statement expected.
platforms/android/app/src/main/assets/app/tns_modules/@schematics/angular/service/files/__name@dasherize@if-flat__/__name@dasherize__.service.spec.ts(15,2): error TS1128: Declaration or statement expected.
platforms/android/app/src/main/assets/app/tns_modules/@schematics/angular/service/files/__name@dasherize@if-flat__/__name@dasherize__.service.ts(6,15): error TS1139: Type parameter declaration expected.
platforms/android/app/src/main/assets/app/tns_modules/@schematics/angular/service/files/__name@dasherize@if-flat__/__name@dasherize__.service.ts(6,26): error TS1005: '>' expected.
platforms/android/app/src/main/assets/app/tns_modules/@schematics/angular/service/files/__name@dasherize@if-flat__/__name@dasherize__.service.ts(6,34): error TS1109: Expression expected.
platforms/android/app/src/main/assets/app/tns_modules/@schematics/angular/service/files/__name@dasherize@if-flat__/__name@dasherize__.service.ts(6,43): error TS1005: ';' expected.
platforms/android/app/src/main/assets/app/tns_modules/@schematics/angular/service/files/__name@dasherize@if-flat__/__name@dasherize__.service.ts(8,17): error TS1005: ';' expected.
platforms/android/app/src/main/assets/app/tns_modules/@schematics/angular/universal/files/src/__main@stripTsExtension__.ts(9,10): error TS1003: Identifier expected.
platforms/android/app/src/main/assets/app/tns_modules/@schematics/angular/universal/files/src/__main@stripTsExtension__.ts(9,11): error TS1110: Type expected.
platforms/android/app/src/main/assets/app/tns_modules/@schematics/angular/universal/files/src/__main@stripTsExtension__.ts(9,35): error TS1109: Expression expected.
<=========----> 71% EXECUTING [25m 15s]
> :app:mergeDebugAssets Expression expected.
> :app:mergeDebugAssetsCUTING [24m 53s]pp/tns_modules/@schematics/angular/universal/files/src/__main@stripTsExtension__.
<=========----> 71% EXECUTING [25m 23s]
<=========----> 71% EXECUTING [25m 24s]ng for file chang_

The app has been compiled in 30 Min !!! 
Finally I saw:
:app:mergeDebugAssetsCUTING [25m 26s]
16:46:28 - File change detected. Starting incremental compilation...
> :app:mergeDebugAssetsCUTING [25m 26s]
<============-> 92% EXECUTING [30m 28s]
> :app:packageDebug

Then I saw again

**:application entry point file not found Please specify in package.json**

What's happening here ?

**Comment by jkod** [comment]
You need to execute with the --bundle flag e.g. `tns run android --bundle` since webpack is used to pick the files.

https://twitter.com/thomascmost/status/1006542436599033857

**Comment by lschaffer** [comment]
thx
