### ISSUE TITLE
How to share imports?

### ISSUE THREAD

**Issue by chrillewoodz** [NativeScript/nativescript-schematics#141]
I can't believe this isn't mentioned anywhere on the internet nor in the official NativeScript docs.

How do you share imports between a web app and a native app?

The following works when running the app in a native environment with `npm run android`:

```
import {App} from '~/app/shared/constants/app.constant';
```

But then if I run it with `ng serve` to run my app in the browser it says 

```
Cannot find module '~/app/shared/constants/app.constant'.
```

If I try to define custom paths in my `tsconfig.json`:

```
"paths": {
    "~/*": [
        "src/*"
    ],
    "*": [
        "./node_modules/tns-core-modules/*",
        "./node_modules/*"
    ],
    "@components/*": ["src/app/shared/components/*"],
    "@constants/*": ["src/app/shared/constants/*"]
}
```

And then doing:

```
import {App} from '@constants/app.constant';
```

Running this with `ng serve` works but GUESS WHAT, it doesn't work when running the app with `npm run android`.

You can't check which platform you're running in either and decide how the imports look because then you get "duplicate imports" error due to the same thing being imported twice in the same file.

**EDIT:**

Also, when trying to use the environment files they appear not to be found either in the `app.module.tns.ts` file when doing `~/environments/environment`, however in `app.module.ts` the import works.. Trying to do `../environments/environment` in `app.module.tns.ts` finds the environment but then trying to read a property from it like this:

```
export function coreFactory(): CoreConfig {

  return {
    api: environment.api // this is a string
  };
}
```

You get an error when running this with `npm run android`:

> Error calling module function

But it works perfectly fine in a web environment using `ng serve`.

It sounds to me like you haven't fully tested the pathing when it comes to imports, the fact that there are no examples that uses imports from nested folders kinda backs me up on that.. 

Can you please give an official solution to this here and then add it to some sort of documentation? Or if this is a bug then please fix it asap 😞

**Comment by sebawita** [comment]
Hi @chrillewoodz,

Thank you for reaching out. I will add this to the documentation, as the solution might not be immediately obvious.
Also, we will refactor the migration schematic to ensure that the paths are only in `tsconfig.json` out of the box.

Luckily, the solution is quite simple.

## Step 1
In `tsconfig.json` add `paths` to `compilerOptions`:
```JSON
"compilerOptions": {
  ...
  "paths": {
    "~/*": [
      "src/*"
    ],
    "@components/*": ["src/app/shared/components/*"],
    "@constants/*": [
      "src/app/shared/constants/*"
    ]
  }
}
```

Also, there is no need to provide the paths for `tns-core-modules`, so you can remove this part:
```JSON
    "*": [
        "./node_modules/tns-core-modules/*",
        "./node_modules/*"
    ],
```

## Step 2
Then remove `paths` from `tsconfig.tns.json`. Make sure to remove the `paths` attribute as a whole and don't leave an empty array. 

Let me know if that works.
If not, can you share a project where you are experiencing the issue?

## Platform specific configurations
Also, if you need specific paths for mobile only (like the `tns-core-modules` were provided), you will need to copy all your paths from `tsconfig.json` to `tsconfig.tns.json` (as TypeScript would override the paths from the parent), then add additional paths to `paths`.

i.e. `tsconfig.tns.json`
```JSON
"compilerOptions": {
  ...
  "paths": {
    "~/*": [
      "src/*"
    ],
    "@components/*": [
      "src/app/shared/components/*"
    ],
    "@constants/*": [
      "src/app/shared/constants/*"
    ],
    "@mobile/*": [
      "src/app/mobile/*"
    ]
  }
}
```

**Comment by chrillewoodz** [comment]
@sebawita Thanks for the reply, I will try this and get back to you once I've gotten around to it.
