### ISSUE TITLE
compatibilty with sidekick

### ISSUE THREAD

**Issue by Serge-SDL** [NativeScript/nativescript-schematics#144]
Hello,

I'm triying to run a basic code shared application (https://www.nativescript.org/blog/how-to-build-a-pwa-an-ios-app-and-an-android-app-from-one-codebase)  with sidekick but got an error:
```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Application entry point file not found. Please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists.\nIf using typescript make sure your entry point file is transpiled to javascript.
```

-> is nativescript-schematics code sharing compatible with sidekick ?

**Comment by chrishaff** [comment]
@Serge-SDL That article does not even mention Sidekick...? New apps generated via Sidekick are not the same structure. IMO it should match what schematics generates - if that's going to be the official story going forward. 

For now you'll just want to use schematics.

**Comment by sis0k0** [comment]
Hi @Serge-SDL, the code-sharing apps work within SideKick if you build them with webpack. Make sure to tick the `webpack` checkbox :)

**Comment by Serge-SDL** [comment]
Ok, works fine, thanks!
