### ISSUE TITLE
Code Sharing Project does not build for Android

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-schematics#151]
@Lightk3ira commented on [Mon Nov 12 2018](https://github.com/NativeScript/NativeScript/issues/6552)

**Environment**
√ Component nativescript has 5.0.0 version and is up to date.
‼ Update available for component tns-core-modules. Your current version is 4.2.1 and the latest available version is 5.0.2.
√ Component tns-android has 5.0.0 version and is up to date.
× Component tns-ios is not installed.

- Operating System: Windows 10 PRO 64 BIT
- OS Build: 17134.345
- Processor: 3.4- ghz
- Installed RAM: 16GB

 - CLI: @angular/cli": "^6.2.0
 - Cross-platform modules: 5.0.0
 - Android Runtime: 5.0.0
 - iOS Runtime: N/A
 - Plugin(s):

**Describe the bug**
The bug happens with a brand new code sharing project on android build. After creating a new code sharing project and running `tns run android -- bundle` or using Nativescript Sidekick the app with fail with errors in the terminal as well as shows logs and exceptions in mobile.

**To Reproduce**
I Installed the latest Node and the NP

M. Android studio is installed on the computer with all SDK's.
Following the steps [here](https://docs.nativescript.org/angular/code-sharing/creating-a-new-project)\
I ran the following commands:

1. `npm i -g @angular/cli`
2.` npm i -g @nativescript/schematics`
3. `ng new -c=@nativescript/schematics sass-project --shared --style=scss`
4. `cd sass-project`
5. `npm install`
6. `tns run android --bundle`

I also tried using NativeScript Sidekick at step 6 on a different attempt.
I have also tried installing all packages to their latest using `@latest`
I have also tried cloud building both from terminal using tns cloud run android --bundle as well as using the NativeScript Sidekick.

**Expected behavior**
As This tutorial shows how to create a new Angular Web and Mobile application template I would assume that Web, Android, and iOS will all build out of the box.

**Sample project**
For the attached project folder I deleted the `node_modules` as the folder size made it too large to upload.

**Additional context**
I have tried to run this tutorial and get a working android build for development for a few days now. I have tried on 2 Windows computers both running Windows 10. as well as 1 Macbook  running High Sierra version 10.13.6

**Terminal Logs:**

ERROR in node_modules/@types/jasmine/index.d.ts(138,47): error TS1005: ';' expected.
node_modules/@types/jasmine/index.d.ts(138,90): error TS1005: '(' expected.
node_modules/@types/jasmine/index.d.ts(138,104): error TS1005: ']' expected.
node_modules/@types/jasmine/index.d.ts(138,112): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,113): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(138,121): error TS1005: ')' expected.
node_modules/@types/jasmine/index.d.ts(138,147): error TS1005: '(' expected.
node_modules/@types/jasmine/index.d.ts(138,162): error TS1005: ']' expected.
node_modules/@types/jasmine/index.d.ts(138,163): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,164): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(138,165): error TS1136: Property assignment expected.
node_modules/@types/jasmine/index.d.ts(138,179): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,183): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(138,208): error TS1005: '{' expected.
node_modules/@types/jasmine/index.d.ts(138,217): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(138,222): error TS1005: ',' expected.
node_modules/@types/jasmine/index.d.ts(138,227): error TS1005: ':' expected.
node_modules/@types/jasmine/index.d.ts(138,228): error TS1109: Expression expected.
node_modules/@types/jasmine/index.d.ts(138,230): error TS1005: ')' expected.

Webpack compilation complete. Watching for file changes.
Webpack build done!

**Mobile Device Crash:**

![image](https://user-images.githubusercontent.com/8987009/48356596-9a05f580-e664-11e8-9130-a0483b200be6.png)

[sass-project.zip](https://github.com/NativeScript/NativeScript/files/2572408/sass-project.zip)

---

@petplan-Pat commented on [Mon Nov 12 2018](https://github.com/NativeScript/NativeScript/issues/6552#issuecomment-438031599)

same

`System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.codeSharing/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: TypeError: Cannot read property 'create' of undefined
System.err: File: "file:///data/data/org.nativescript.codeSharing/files/app/vendor.js, line: 12284, column: 14
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.codeSharing/files/app/vendor.js', line: 12284, column: 15`

---

@skopekreep commented on [Tue Nov 13 2018](https://github.com/NativeScript/NativeScript/issues/6552#issuecomment-438046602)

After digging for a while with the same issue I found the following that seems to resolve the issue.

According to this [thread](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30310#issuecomment-436926217) the reason for the @types/jasmine errors that @Lightk3ira posted above is that "@types/jasmine": "~2.8.6" updates to 2.8.11, which is incompatible with Typescript 2.7.

After changing ```"@types/jasmine": "~2.8.6"```

to ```"@types/jasmine": "2.8.6"``` to pin the version to 2.8.6 the app ran as expected.

Note that this also fixes the same errors that appeared during an iOS build with 2.8.11.

---

@Lightk3ira commented on [Tue Nov 13 2018](https://github.com/NativeScript/NativeScript/issues/6552#issuecomment-438112129)

That is the version the nativescript  and angular team had in their code sharing project. If that is the issue then they did not test that updating the packages did not break anything.

---

@Lightk3ira commented on [Tue Nov 13 2018](https://github.com/NativeScript/NativeScript/issues/6552#issuecomment-438112435)

As well as Jasmine is just a testing framework. That should not have anything to do with the on create failrue. Will test and see

---

@skopekreep commented on [Tue Nov 13 2018](https://github.com/NativeScript/NativeScript/issues/6552#issuecomment-438132954)

The breaking change is with @types/jasmine, which only happened 7 days ago  [(see version history)](https://www.npmjs.com/package/@types/jasmine). According to the thread linked in my previous post, one of the updates to the package requires Typescript > 2.7.2.  Arguably, per semver guidelines, this was a breaking change and should have been named something like 3.0.0 instead of 2.8.x.

Now, why exactly this leads to the error about "create failure", I'm not completely sure, but it is a typescript error that exists prior to building.  I'll defer to someone more familiar with the inner workings of NS. 

---

@NickIliev commented on [Tue Nov 13 2018](https://github.com/NativeScript/NativeScript/issues/6552#issuecomment-438163308)

@Lightk3ira @skopekreep thank you guys for bringing this one into our attention.  The issue is already addressed [via this PR ](https://github.com/NativeScript/nativescript-schematics/pull/146)and will be fixed with the upcoming version of nativescript-schematics.

Meanwhile, if you want to address and fix the issue in already create shared projects then open the package.json and bump the versions of 
- `typescript` to `~2.8.0` or above
- `tns-core-modules` to `5.0.2`
- `nativescript-dev-webpack` to `0.17.0` and then update the config files via [the upgrade script](https://docs.nativescript.org/angular/releases/upgrade-instructions#upgrading-webpack)

**Comment by carrbrpoa** [comment]
Hey @NickIliev, I'm not sure if it's related, but maybe it is.
Everything upgraded, fresh new schematics project just to test (`ng new MYProj --collection @nativescript/schematics --shared --sample`), with some changed packages:

```
{
  "name": "MYProj",
  "nativescript": {
    "id": "...",
    "tns-android": {
      "version": "5.0.0"
    }
  },
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "android": "tns run android --bundle",
    "ios": "tns run ios --bundle"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.0.3",
    "@angular/common": "~7.0.3",
    "@angular/compiler": "~7.0.3",
    "@angular/core": "~7.0.3",
    "@angular/forms": "~7.0.3",
    "@angular/http": "~7.0.3",
    "@angular/platform-browser": "~7.0.3",
    "@angular/platform-browser-dynamic": "~7.0.3",
    "@angular/router": "~7.0.3",
    "core-js": "^2.5.7",
    "nativescript-angular": "~7.0.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.3.3",
    "tns-core-modules": "5.0.2",
    "zone.js": "^0.8.26",
    "@nstudio/nativescript-camera-plus": "^1.1.3",
    "base-64": "^0.1.0",
    "nativescript-appversion": "^1.4.1",
    "nativescript-couchbase": "^1.0.18",
    "nativescript-drop-down": "^4.0.1",
    "nativescript-floatingactionbutton": "^5.0.0",
    "nativescript-geolocation": "^4.3.1",
    "nativescript-gif": "^4.0.2",
    "nativescript-image-filters": "^2.2.0",
    "nativescript-imagepicker": "^6.0.4",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-powerinfo": "^1.0.7",
    "nativescript-ripple": "^2.1.0",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-listview": "^3.8.0",
    "nativescript-ui-sidedrawer": "^5.0.0",
    "nativescript-webview-interface": "^1.4.2",
    "nativescript-plugin-firebase": "^7.4.1"
  },
  "devDependencies": {
    "@angular/cli": "^7.0.5",
    "@angular/compiler-cli": "~7.0.0",
    "@angular-devkit/build-angular": "^0.10.5",
    "@nativescript/schematics": "~0.4.0",
    "@types/node": "~10.12.7",
    "codelyzer": "~4.5.0",
    "nativescript-dev-typescript": "~0.7.5",
    "nativescript-dev-webpack": "^0.18.0",
    "ts-loader": "^5.3.0",
    "protractor": "~5.4.1",
    "ts-node": "~7.0.1",
    "tslint": "~5.11.0",
    "typescript": "~3.1.1"
  }
}
```
Did run webpack upgrade sccript task.
Problem: app installs but doesn't run. All I see the splash screen forever.
Full terminal output:
```
> tns run android --bundle

Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Executing before-liveSync hook from W:\Me\Projetos\NativeScript\MYProj\hooks\before-liveSync\nativescript-angular-sync.js
Executing before-watchPatterns hook from W:\Me\Projetos\NativeScript\MYProj\hooks\before-watchPatterns\nativescript-dev-typescript.js
Executing before-watchPatterns hook from W:\Me\Projetos\NativeScript\MYProj\hooks\before-watchPatterns\nativescript-dev-webpack.js
Executing before-watch hook from W:\Me\Projetos\NativeScript\MYProj\hooks\before-watch\nativescript-dev-typescript.js
Hook skipped because bundling is in progress.
Executing before-watch hook from W:\Me\Projetos\NativeScript\MYProj\hooks\before-watch\nativescript-dev-webpack.js
Running webpack for Android...
clean-webpack-plugin: W:\Me\Projetos\NativeScript\MYProj\platforms\android\app\src\main\assets\app\**\* has been removed.
File change detected. Starting incremental webpack compilation...

webpack is watching the files…

Hash: d6a7763d5e26012c49fd
Version: webpack 4.19.1
Time: 12301ms
Built at: 2018-11-13 22:50:12
                                                 Asset       Size  Chunks
  Chunk Names
         App_Resources/Android/drawable-xhdpi/icon.png   10.4 KiB          [emitted]
                                             bundle.js   31.5 KiB  bundle  [emitted]  bundle
             App_Resources/Android/AndroidManifest.xml   1.36 KiB          [emitted]
                      App_Resources/Android/app.gradle  547 bytes          [emitted]
    App_Resources/Android/drawable-hdpi/background.png   3.42 KiB          [emitted]
          App_Resources/Android/drawable-hdpi/icon.png    6.8 KiB          [emitted]
          App_Resources/Android/drawable-hdpi/logo.png   32.4 KiB          [emitted]
    App_Resources/Android/drawable-ldpi/background.png   1.31 KiB          [emitted]
          App_Resources/Android/drawable-ldpi/icon.png   3.23 KiB          [emitted]
          App_Resources/Android/drawable-ldpi/logo.png   9.95 KiB          [emitted]
    App_Resources/Android/drawable-mdpi/background.png   1.89 KiB          [emitted]
          App_Resources/Android/drawable-mdpi/icon.png   3.42 KiB          [emitted]
          App_Resources/Android/drawable-mdpi/logo.png   15.8 KiB          [emitted]
App_Resources/Android/drawable-nodpi/splash_screen.xml  304 bytes          [emitted]
   App_Resources/Android/drawable-xhdpi/background.png   5.26 KiB          [emitted]
                                             vendor.js   4.77 MiB  vendor  [emitted]  vendor
         App_Resources/Android/drawable-xhdpi/logo.png     54 KiB          [emitted]
  App_Resources/Android/drawable-xxhdpi/background.png   10.3 KiB          [emitted]
        App_Resources/Android/drawable-xxhdpi/icon.png   20.3 KiB          [emitted]
        App_Resources/Android/drawable-xxhdpi/logo.png    116 KiB          [emitted]
 App_Resources/Android/drawable-xxxhdpi/background.png   3.87 KiB          [emitted]
       App_Resources/Android/drawable-xxxhdpi/icon.png   73.8 KiB          [emitted]
       App_Resources/Android/drawable-xxxhdpi/logo.png    193 KiB          [emitted]
            App_Resources/Android/google-services.json   1.13 KiB          [emitted]
           App_Resources/Android/values-v21/colors.xml  104 bytes          [emitted]
           App_Resources/Android/values-v21/styles.xml  902 bytes          [emitted]
               App_Resources/Android/values/colors.xml  237 bytes          [emitted]
               App_Resources/Android/values/styles.xml   1.68 KiB          [emitted]
                                          package.json  134 bytes          [emitted]
                                            starter.js   39 bytes          [emitted]
                                   tns-java-classes.js    0 bytes          [emitted]
Entrypoint bundle = vendor.js bundle.js
[../$$_lazy_route_resource lazy recursive] ../$$_lazy_route_resource lazy namespace
object 160 bytes {bundle} [built]
[./app.css] 276 bytes {bundle} [built]
[./app/app-routing.module.ts] 1.06 KiB {bundle} [built]
[./app/app.component.css] 19 bytes {bundle} [built]
[./app/app.component.html] 64 bytes {bundle} [built]
[./app/app.component.ts] 982 bytes {bundle} [built]
[./app/app.module.ts] 1.76 KiB {bundle} [built]
[./app/app.routes.ts] 239 bytes {bundle} [built]
[./app/barcelona/barcelona.common.ts] 481 bytes {bundle} [built]
[./app/barcelona/barcelona.module.ts] 1.51 KiB {bundle} [built]
[./app/home/home.component.css] 19 bytes {bundle} [built]
[./app/home/home.component.html] 273 bytes {bundle} [built]
[./app/home/home.component.ts] 1.28 KiB {bundle} [built]
[./main.ns.ts] 1.22 KiB {bundle} [built]
[./package.json] 123 bytes {bundle} [optional] [built]
    + 409 hidden modules
Webpack compilation complete. Watching for file changes.
Webpack build done!
Copying template files...
Platform android successfully added. v5.0.0
Executing before-checkForChanges hook from W:\Me\Projetos\NativeScript\MYProj\hooks\before-checkForChanges\firebase-copy-google-services.js
nativescript-plugin-firebase: W:\Me\Projetos\NativeScript\MYProj\platforms\android\.pluginfirebaseinfo not found, forcing prepare!
Executing before-shouldPrepare hook from W:\Me\Projetos\NativeScript\MYProj\hooks\before-shouldPrepare\nativescript-dev-webpack.js
Executing before-prepare hook from W:\Me\Projetos\NativeScript\MYProj\hooks\before-prepare\nativescript-dev-typescript.js
Hook skipped because either bundling or livesync is in progress.
Executing before-prepare hook from W:\Me\Projetos\NativeScript\MYProj\hooks\before-prepare\nativescript-plugin-firebase.js
Preparing project...
Executing before-prepareJSApp hook from W:\Me\Projetos\NativeScript\MYProj\hooks\before-prepareJSApp\nativescript-dev-webpack.js
Project successfully prepared (Android)
Executing after-prepare hook from W:\Me\Projetos\NativeScript\MYProj\hooks\after-prepare\firebase-build-gradle.js
Configure firebase
Executing after-prepare hook from W:\Me\Projetos\NativeScript\MYProj\hooks\after-prepare\firebase-copy-google-services.js
Copy W:\Me\Projetos\NativeScript\MYProj\App_Resources\Android\google-services.json to W:\Me\Projetos\NativeScript\MYProj\platforms\android\app\google-services.json.
Executing after-prepare hook from W:\Me\Projetos\NativeScript\MYProj\hooks\after-prepare\nativescript-dev-webpack.js
Executing after-prepare hook from W:\Me\Projetos\NativeScript\MYProj\hooks\after-prepare\nativescript-plugin-firebase.js
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from W:\Me\Projetos\NativeScript\MYProj\App_Resources\Android\app.gradle
Using support library version 28.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: W:\Me\Projetos\NativeScript\MYProj\node_modules\@nstudio\nativescript-camera-plus\platforms\android\nativescript-camera-plus.aar
         + adding aar plugin dependency: W:\Me\Projetos\NativeScript\MYProj\node_modules\@nstudio\nativescript-camera-plus\platforms\android\nativescript_camera_plus.aar
         + adding aar plugin dependency: W:\Me\Projetos\NativeScript\MYProj\node_modules\nativescript-geolocation\platforms\android\nativescript_geolocation.aar
         + adding aar plugin dependency: W:\Me\Projetos\NativeScript\MYProj\node_modules\nativescript-ui-listview\platforms\android\TNSListView-release.aar
         + adding aar plugin dependency: W:\Me\Projetos\NativeScript\MYProj\node_modules\nativescript-ui-sidedrawer\platforms\android\TNSSideDrawer-release.aar
         + adding jar plugin dependency: W:\Me\Projetos\NativeScript\MYProj\node_modules\nativescript-webview-interface\platforms\android\WebViewInterface.jar
         + adding aar plugin dependency: W:\Me\Projetos\NativeScript\MYProj\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
         + adding aar plugin dependency: W:\Me\Projetos\NativeScript\MYProj\node_modules\nativescript-ui-core\platforms\android\TNSCore-release.aar
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Project successfully built.
Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Unable to apply changes on device: emulator-5554. Error is: Socket connection timed
out..
Executing after-watch hook from W:\Me\Projetos\NativeScript\MYProj\hooks\after-watch\nativescript-dev-typescript.js
Executing after-watch hook from W:\Me\Projetos\NativeScript\MYProj\hooks\after-watch\nativescript-dev-webpack.js
Stopping webpack watch
Executing after-watch hook from W:\Me\Projetos\NativeScript\MYProj\hooks\after-watch\nativescript-dev-typescript.js
Executing after-watch hook from W:\Me\Projetos\NativeScript\MYProj\hooks\after-watch\nativescript-dev-webpack.js
Stopping webpack watch
```

PS1: the line that starts with "Unable to apply changes" occurs after some seconds of waiting for emulator to actually starts the app;
PS2: there are some packages added from my "real project";
PS3: ommited package id.

**Comment by Lightk3ira** [comment]
@NickIliev I set those packages to the versions you specified and the android build still fails with 'Unable to start activity', TypeError: Cannot read property of undefined.

**Comment by Lightk3ira** [comment]
@NickIliev Also I got this error: 
`ERROR in The Angular Compiler requires TypeScript >=2.7.2 and <2.8.0 but 3.1.6 was found instead.`

NPM could not find any package of 2.8.0 when I had that set

**Comment by Lightk3ira** [comment]
This is the package.json I used that seems to be working fine for builds. Still though I I think the different teams should try to corrdinate better so we dont have these issues if possible.


```
{
  "name": "sass-project",
  "nativescript": {
    "id": "org.nativescript.sass-project",
    "tns-android": {
      "version": "5.0.0"
    }
  },
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "android": "tns run android --bundle",
    "ios": "tns run ios --bundle"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "core-js": "^2.5.4",
    "nativescript-angular": "~6.1.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^6.0.0",
    "tns-core-modules": "~5.0.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.8.0",
    "@angular/cli": "^6.2.0",
    "@angular/compiler-cli": "^7.0.3",
    "@nativescript/schematics": "~0.4.0",
    "@types/jasmine": "2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.17.0",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "^3.1.6"
  }
}
```

**Comment by NickIliev** [comment]
@Lightk3ira the issue is now resolved and a new version of nativescript-schematics it published with the fix. Just update your nativescript-schematics versions and create new project.

If you want to fix a project that was already created then bump the TypeScript version to 2.8.0 and above.

Resolved via [https://github.com/NativeScript/nativescript-schematics/pull/146](https://github.com/NativeScript/nativescript-schematics/pull/146)

**Comment by jfalmoguera** [comment]
I've updated the nativescript-schematics and Im getting the error below. 

Machine settings: 

TNS Vesion: 5
Angular CLI: 7.0.3
Node: 10.13.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.3
@angular-devkit/core         7.0.3
@angular-devkit/schematics   7.0.3
@schematics/angular          7.0.3
@schematics/update           0.10.3
rxjs                         6.3.3
typescript                   3.1.3


**ng new -c=@nativescript/schematics sharedTest --shared --style=scss**

**ERROR -->**

<--- Last few GCs --->

[9208:000002741A5AD690]   272821 ms: Mark-sweep 1354.6 (1454.0) -> 1340.0 (1454.0) MB, 61.8 / 0.0 ms  (average mu = 0.310, current mu = 0.282) allocation failure scavenge might not succeed
[9208:000002741A5AD690]   272896 ms: Mark-sweep 1354.6 (1454.0) -> 1340.1 (1454.5) MB, 51.5 / 0.0 ms  (average mu = 0.312, current mu = 0.315) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x0179acb1e6e1 <JSObject>
    0: builtin exit frame: new Date(aka Date)(this=0x03eda7e02801 <the_hole>,0x03eda7e02801 <the_hole>)

    1: ConstructFrame [pc: 0000011B31F0D385]
    2: _rename [00000255C190C679] [C:\Users\josef\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\virtual-fs\host\memory.js:~149] [pc=0000011B324E5171](this=0x02b3bae90c99 <SimpleMemoryHost map = 00000334A30C7901...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF62005ECE5
 2: 00007FF620038196
 3: 00007FF620038BA0
 4: 00007FF6202C8D5E
 5: 00007FF6202C8C8F
 6: 00007FF6208069D4
 7: 00007FF6207FD137
 8: 00007FF6207FB6AC
 9: 00007FF620804627
10: 00007FF6208046A6
11: 00007FF6203AF339
12: 00007FF6203AF193
13: 00007FF6205E8DA9
14: 00007FF6206C018A
15: 00007FF6206BFA5B
16: 0000011B31F5C721
