### ISSUE TITLE
 Error Creating shared project: JavaScript heap out of memory

### ISSUE THREAD

**Issue by jfalmoguera** [NativeScript/nativescript-schematics#153]
I've updated to the last version of nativescript-schematics and Im getting the error below.

Machine settings: 

TNS Vesion: 5
Angular CLI: 7.0.3
Node: 10.13.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.3
@angular-devkit/core         7.0.3
@angular-devkit/schematics   7.0.3
@schematics/angular          7.0.3
@schematics/update           0.10.3
rxjs                         6.3.3
typescript                   3.1.3

**ng new -c=@nativescript/schematics sharedTest --shared --style=scss**

**ERROR -->**

<--- Last few GCs --->

[9208:000002741A5AD690]   272821 ms: Mark-sweep 1354.6 (1454.0) -> 1340.0 (1454.0) MB, 61.8 / 0.0 ms  (average mu = 0.310, current mu = 0.282) allocation failure scavenge might not succeed
[9208:000002741A5AD690]   272896 ms: Mark-sweep 1354.6 (1454.0) -> 1340.1 (1454.5) MB, 51.5 / 0.0 ms  (average mu = 0.312, current mu = 0.315) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x0179acb1e6e1 <JSObject>
    0: builtin exit frame: new Date(aka Date)(this=0x03eda7e02801 <the_hole>,0x03eda7e02801 <the_hole>)

    1: ConstructFrame [pc: 0000011B31F0D385]
    2: _rename [00000255C190C679] [C:\Users\josef\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\virtual-fs\host\memory.js:~149] [pc=0000011B324E5171](this=0x02b3bae90c99 <SimpleMemoryHost map = 00000334A30C7901...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF62005ECE5
 2: 00007FF620038196
 3: 00007FF620038BA0
 4: 00007FF6202C8D5E
 5: 00007FF6202C8C8F
 6: 00007FF6208069D4
 7: 00007FF6207FD137
 8: 00007FF6207FB6AC
 9: 00007FF620804627
10: 00007FF6208046A6
11: 00007FF6203AF339
12: 00007FF6203AF193
13: 00007FF6205E8DA9
14: 00007FF6206C018A
15: 00007FF6206BFA5B
16: 0000011B31F5C721

_Originally posted by @jfalmoguera in https://github.com/NativeScript/nativescript-schematics/issues/151#issuecomment-438576598_

Edit:

**Fixed** after updating the angular/cli to the last version (7.0.5).

**Comment by craigstanton** [comment]
I get this too. On MacBook Pro with 16Gb, it must be able to do this. Is there a way to allocate more memory to this process?
