### ISSUE TITLE
Extending Application and Activity

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-schematics#155]
@bagnos commented on [Sat Nov 17 2018](https://github.com/NativeScript/NativeScript/issues/6571)

How Can I extend Application and Activity in a code-sharing project? There is no documentation about this kind of project, using the official documentation we get a ClassNotFoundException.

**Comment by NickIliev** [comment]
@bagnos the only thing that is different if that you might need to change the path to your extended application and activity files in the `webpack.config.js`. If using TypeScript to extend the application/activity you should also enable the experimentalDecorations in the tsconfig of the NativeScript app.


Here are the steps I've taken to extend the application in shared project:

- [Create new shared project ](https://docs.nativescript.org/angular/code-sharing/creating-a-new-project)(or use your already created one)
- in `src/app/home` create the extended Application file `application.android.js` (using JavaScript file). Additional details [here](https://docs.nativescript.org/angular/core-concepts/android-runtime/advanced-topics/extend-application-activity)

```
const superProto = android.app.Application.prototype;

// the first parameter of the `extend` call defines the package and the name for the native *.JAVA file generated. 
android.app.Application.extend("org.myApp.Application", {
    onCreate: function() {
        superProto.onCreate.call(this);
        console.log("Overwritten application");
        // At this point modules have already been initialized

        // Enter custom initialization code here
    },
    attachBaseContext: function(base) {
        superProto.attachBaseContext.call(this, base);
        // This code enables MultiDex support for the application (if needed)
        // android.support.multidex.MultiDex.install(this);
    }
});
```

- In the `webpack.config.js` introduce the entry property in the config section
```
entry: {
    bundle: entryPath,
    application: resolve("./src/app/application.android.js"),
},
```

- Remove the platforms folder and rebuild with `--bundle`
```
rm -rf platforms
tns run android --bundle
```

Overall the same steps are applied when extending activity but the activity is added in `appComponents` in `webpack.config.js` (just as the instructions given [in the article)](https://docs.nativescript.org/angular/core-concepts/android-runtime/advanced-topics/extend-application-activity) and with the modified path.

Here is how I've added the extended activity from `activity.android.js` in `webpack.config.js`

```
const appComponents = [
    "tns-core-modules/ui/frame",
    "tns-core-modules/ui/frame/activity",
    resolve(__dirname, "./src/app/activity.android.js"),
];
```

All of the above can be seen in [this test project](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/test/issue-6571)

**Comment by bagnos** [comment]
hi,

I make the similiar typescript file application.android.ts, when I run the
project I get the following error:

ERROR in src/app/application.android.ts(4,2): error TS2304: Cannot find
name 'JavaProxy'.

Before that error I got this one fixed by the below configuration:

ERROR in ./app/application.android.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):

tsconfig.tns.json
,
"files": [
"./src/app/application.android.ts",
]

kind regards,

Simone
