### ISSUE TITLE
Deployment error while creating new app with schematics.

### ISSUE THREAD

**Issue by babujoym** [NativeScript/nativescript-schematics#156]
This error is only happening when we create a native app from scratch with the command.

ng new — collection=@nativescript/schematics — name=new-app — shared

This is not happening, when we create a new angular app using ng new and then use 
ng add @nativescript/schematics

Below is the Stack Trace

Skipping prepare.
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.newapp/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed
System.err:
System.err: TypeError: Cannot read property ‘create’ of undefined
System.err: File: “file:///data/data/org.nativescript.newapp/files/app/vendor.js, line: 12299, column: 14
System.err:
System.err: StackTrace:
System.err: Frame: function:’’, file:’file:///data/data/org.nativescript.newapp/files/app/vendor.js’, line: 12299, column: 15
System.err: Frame: function:’push…/node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase.navigate’, file:’file:///data/data/org.nativescript.newapp/files/app/vendor.js’, line: 19827, column: 30
System.err: Frame: function:’push…/node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.setActivityContent’, file:’file:///data/data/org.nativescript.newapp/files/app/vendor.js’, line: 21077, column: 30
System.err: Frame: function:’push…/node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.onCreate’, file:’file:///data/data/org.nativescript.newapp/files/app/vendor.js’, line: 20936, column: 14
System.err: Frame: function:’push…/node_modules/tns-core-modules/ui/frame/activity.js.NativeScriptActivity.onCreate’, file:’file:///data/data/org.nativescript.newapp/files/app/vendor.js’, line: 18923, column: 25
System.err:
System.err: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
System.err: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
System.err: at android.app.ActivityThread.-wrap12(ActivityThread.java)
System.err: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
System.err: at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: at android.os.Looper.loop(Looper.java:154)
System.err: at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err: at java.lang.reflect.Method.invoke(Native Method)
System.err: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
System.err: Caused by: com.tns.NativeScriptException:
System.err: Calling js method onCreate failed

**Comment by sebawita** [comment]
hey @babujoym, could you update the global npm package for `@nativescript/schematics` and try again?

I think that when you run `ng add` the Angular CLI will install the schematic provided with the `-c`, which will automatically use the latest version. However `ng new` relies on the globally installed npm package, which doesn't guarantee that it is the latest one.

**Comment by babujoym** [comment]
I am using I believe the latest version of nativescript/schematics which is 0.4.0 and i think this version has the issue.

**Comment by Swoox** [comment]
I had this problem to did you use `tns doctor`?

**Comment by babujoym** [comment]
nope.. I will try it out.

**Comment by NickIliev** [comment]
@babujoym closing this one due to inactivity but please do let me know if you are still experiencing this issue after updating to latest and running `tns doctor`
