### ISSUE TITLE
Adding nativescript to an existing Angular 6 project

### ISSUE THREAD

**Issue by bytelabsco** [NativeScript/nativescript-schematics#160]
I've gone through the NS documentation, as well as other how-tos on the web, and cannot figure out how to add @nativescript/schematics to my existing angular 6 project, without it upgrading to Angular 7.  Unfortunately my project has external dependencies that prevent an upgrade to Angular 7.  I looked through the version history of @nativescript/schematics, but couldn't determine which one will force me to upgrade to NG7.  Any advice?

**Comment by bytelabsco** [comment]
It looks like I can manually downgrade the version of nativescript-angular after adding the schematic to prevent the warnings about the angular version differences

**Comment by sebawita** [comment]
Yeah, starting from Angular 7, we might add a map that will detect the version of Angular that you are using and apply the correct version of `nativescript-angular` and any relevant libraries.
