### ISSUE TITLE
ng new --collection=@nativescript/schematics not doing anything

### ISSUE THREAD

**Issue by JonasJW** [NativeScript/nativescript-schematics#165]
**Environment**
 - CLI: Anuglar 

I can't use the command `ng new --collection=@nativescript/schematics my-shared-app --shared`. It won't do anything for me. The `--collection=@nativescript/schematics` part causes this problem for me. When I delete it, it works. And yes I have done `npm i -g @nativescript/schematics` before.

**Comment by mjohn314** [comment]
I was just having this issue as well. I updated my angular cli `npm i -g @angular/cli` and the command started working.

**Comment by JonasJW** [comment]
Thanks @mjohn314  that worked!
