### ISSUE TITLE
The configured `baseUrl` is not respected when resolving import paths

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/nativescript-schematics#172]
Thanks, @decmurphy for [reporting](https://github.com/NativeScript/nativescript-schematics/issues/117#issuecomment-448196154) the problem!

**Environment**
 - Angular: 7.1.0
 - Plugins: @nativescript/schematics 0.4.0

**Describe the bug**
The `ng add` command crashes with:
```
Could not find bootstrapped module.
```
when using custom `baseUrl` and absolute paths for the entry NgModule (`app.module`) or the entry component (`app.component`).

**Workaround**
Use relative imports for `app.module.ts` and `app.component.ts`.

**To Reproduce**
1. Create new Angular web project:
``` bash
ng new leapp
```

2. Configure the `baseUrl` in the `tsconfig.json`:
``` json
{
  "compilerOptions": {
    "baseUrl": "./src",
    ...
  }
}
```

3. Import `app.component` with absolute path in `app.module.ts`:
``` ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from 'app/app.component';

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

4. Try to add NativeScript to the project:
```
ng add @nativescript/schematics
```

**Current behavior**
We are not taking the `baseUrl` into account when resolving the import paths.

**Expected behaviour**
The code causing the problem is in the [`getEntryComponentMetadata`](https://github.com/NativeScript/nativescript-schematics/blob/master/src/angular-project-parser.ts#L181) function:
``` ts
  const importPath = findImportPath(source, className);


  const entryModuleDir = dirname(entryModulePath);
  const path = join(entryModuleDir, importPath) + '.ts';
```
The `importPath` for `AppComponent` is `app/app.component`. The `entryModuleDir` is `src/app`. The `join` function returns `src/app/app/app.component` which is obviously wrong and later causes the `Cannot find module` error.
The right behavior would be to detect that `app/app.component` is an absolute path and join it with the configured `baseUrl`.

**Sample project**
https://github.com/sis0k0/baseurl-ng-add-ns

Follows up #117.

**Comment by nghoanghiep** [comment]
I worked around by copying  app.component.ts to a new sub app directory

**Comment by JoelBalmer** [comment]
Thank you so much for this thread!

The reason mine wasn't working is because of the paths I'd defined here:

```
// tsconfig.json
"compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@app/*": [ "src/app/*" ],
      "@app-environments/*": [ "src/environments/*" ],
    }
```

And how I was using them here:

```
// main.ts
import { AppModule } from '@app/app.module';
```

```
// app.module.ts
import { AppComponent } from '@app/app.component';
```

So these are the changes I made to get it working:

```
// main.ts
import { AppModule } from './app/app.module';
```

```
// app.module.ts
import { AppComponent } from './app.component';
```

Hope that helps someone else as well!
