### ISSUE TITLE
nativescript-dev-webpack

### ISSUE THREAD

**Issue by iMarwan-k** [NativeScript/nativescript-schematics#20]
Hi, in the package.json file, the devDependencies "nativescript-dev-webpack" is assigned to "github:nativescript/nativescript-dev-webpack#sis0k0/platform-host" and that cause a problem when you run npm i

so what version of "nativescript-dev-webpack" we should use?

Thanks
Marwan

**Comment by vchimev** [comment]
Hey @iMarwan-k,

the [sis0k0/platform-host](https://github.com/NativeScript/nativescript-dev-webpack/pull/539) branch referenced in the `package.json` file was merged and released in *nativescript-dev-webpack@0.13.0* which version you could use.

It will be updated in here shortly.
