### ISSUE TITLE
Provide option to discard `moduleId: module.id` from newly created components

### ISSUE THREAD

**Issue by ph55** [NativeScript/nativescript-schematics#218]
Since there is an option to run and build application with webpack, there should be option to not add `moduleId: module.id` in components.

As suggestion I would rely on `nativescript-dev-webpack` package to check if it `moduleId: module.id` should be added.

**Comment by sis0k0** [comment]
Thanks for the suggestions, @ph55! Since NativeScript 6.0 is webpack-only, `nativescript-schematics` won't add `moduleId` to the components metadata starting with version `0.7.0` (yet to be released).
