### ISSUE TITLE
Currently we are aware that @nativescript/schematics does not work with Angular 8.0.0. We are actively working on an update!

### ISSUE THREAD

**Issue by Prefix1802** [NativeScript/nativescript-schematics#255]
Hi,

Is this issue fixed? Does schematics work with Angular 8?

**Comment by endarova** [comment]
Hi @Prefix1802 ,
The latest @nativescript/schematics supports Angular 8.

**Comment by bearoutthere** [comment]
Got it working.  The only issue so far was the new way Angular 8 lazy loads modules.  You can see the solution [here](https://www.nativescript.org/blog/lazy-loading-in-nativescript-angular-8.0)

**Comment by Prefix1802** [comment]
Thanx for the replies. The problems i was having were not caused by schematics but by my existing web project. My tnsconfig.app.json is in src with a baseUrl of "./". And somehow when you use paths you can not refer to a folder in the parent dir. e.g. @src mapping to ../src does not work.

I have yet to find a soultions for this. For example download NGX-Admin, add schematics and the project does not work anymore. But that's something i will take up with the makers of NGX-Admin.

**Comment by Fatme** [comment]
I'm closing this as the latest `@nativescript/schematics` works with `Angular 8`

**Comment by Prefix1802** [comment]
For those who are using the template ngx admin with nativescript/schematics:

I got it working with a few tweaks.

install ngx admin master,
ng add @nativescript/schematics
add "baseUrl": "." in tsconfig.json before paths.
In main.tns.ts, app.module.tns.ts, app-routing.module.tns.ts rename src to @src

Now your mobile app is working, but for ngx-admin web you need to do these additional steps.

in tsconfig.app.json comment out baseURL and the files section.
in app.module.ts rename src to @src
in app-routing.module.ts add @src/ to import('app/pages/pages.module')

Sidenote: These instructions are for use with ngx admin. When u start an empty angular project, import nebular and install nativescript/schematics, you do not need to do this, works out of the box.
