### ISSUE TITLE
A merge conflicted on path "/nsconfig.json"

### ISSUE THREAD

**Issue by MrCroft** [NativeScript/nativescript-schematics#27]
When I run `ng add @nativescript/schematics` on an existing web app, I get:
```
A merge conflicted on path "/nsconfig.json".
```

The web app is built with CLI **6.1.0-rc.0**
Nativescript schematics version: **0.1.3**

Repro steps:
Make sure that version 6.1.0-rc.0 of the Angular CLI is installed.
>ng new abc --style scss --routing
>cd abc
>ng add @nativescript/schematics

(`--styles` and `--routing` shouldn't matter I guess, but I always create the app with those flags)

**Comment by MrCroft** [comment]
Hmm... just tested with `@angular/cli@6.1.0-beta.0` (same like in the webinar video I was watching) and it worked (adding v0.1.3 of schematics).
Not sure if this would be just a Angular CLI issue, or if the schematics would also need to provide something else for 6.1.0-rx.0.

**Comment by sis0k0** [comment]
Hey @MrCroft, this problem was indeed introduced with `@angular/cli@6.1.0-rc.0`. While, we're working on fixing it, you can use `@angular/cli@6.1.0-beta.0`.

**Comment by sis0k0** [comment]
Hi again! The problems are resolved in `@angular-devkit/schematics` and will be released in the next `rc` version.
