### ISSUE TITLE
Update to Angular 9

### ISSUE THREAD

**Issue by lucasrabelo** [NativeScript/nativescript-schematics#275]
Will you guys release an update of this to angular 9?

**Comment by Prefix1802** [comment]
I read that nativescript 6.4 is also not working with Angular 9.

https://www.nativescript.org/blog/nativescript-6.4-has-just-landed#comments

**Comment by Valera1980** [comment]
Hi guys. Is where some release date  NS + ang 9?

**Comment by hrueger** [comment]
Although nativescript-angular should be compatible with Angular 9 now, I get `Failed to find generated component file /sidebar.component.scss. Please contact the @nativescript/schematics author.` when I run `ng generate component _components/sidebar` ...
I assume this is because of Angular 9

**Comment by d-koppenhagen** [comment]
Hey Guys, running the actual schematic + proceeding all the steps described here should get things working for now:
https://github.com/NativeScript/nativescript-angular/wiki/Updating-and-developing-for-@nativescript-angular-v9-with-Ivy-or-without

Be also sure:
- to change all deep imports from `nativescript-angular/<whatever>` to the new scoped package `@nativescript/angular`
- furthermore the imports from `tns-core-modules/` has been changed to `@nativescript/core`.

this isn't a fix for the actual schematics yet but at least things will work again :)
