### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' in

### ISSUE THREAD

**Issue by alexander171294** [NativeScript/nativescript-schematics#28]
Hi, im trying to serve my Angular6/nativescript-schematics shared code, using this:

`ng serve `

(For publish in localhost:4200), then the first code work fine, but i add a stompjs/websockets client and it breaks,

This is the error:

```
ERROR in ./node_modules/debug/src/node.js
Module not found: Error: Can't resolve 'fs' in '/Users/alexander.eberle/git/web-poker/frontend/pokerclient/node_modules/debug/src'
ERROR in ./node_modules/eventsource/lib/eventsource.js
Module not found: Error: Can't resolve 'http' in '/Users/alexander.eberle/git/web-poker/frontend/pokerclient/node_modules/eventsource/lib'
ERROR in ./node_modules/eventsource/lib/eventsource.js
Module not found: Error: Can't resolve 'https' in '/Users/alexander.eberle/git/web-poker/frontend/pokerclient/node_modules/eventsource/lib'
ERROR in ./node_modules/debug/src/node.js
Module not found: Error: Can't resolve 'tty' in '/Users/alexander.eberle/git/web-poker/frontend/pokerclient/node_modules/debug/src'
ERROR in ./node_modules/stompjs/lib/stomp-node.js
Module not found: Error: Can't resolve 'websocket' in '/Users/alexander.eberle/git/web-poker/frontend/pokerclient/node_modules/stompjs/lib'
```

i tryed the same configuration in a clean angular project (without nativescript-schematics) and work fine, but in shared version isn't work.

I understand if you say me thats not work in the ios / android version. it's fine (because I need a specific code for these platforms), but on the web version it should work.

Any ideas?

Thanks, and sorry for my bad english, i only speak spanish :P

Edit:

Im using last version of nativescript and angular, and check the dependencies, you can check the code here:
https://github.com/alexander171294/web-poker/tree/master/frontend/pokerclient

Thanks!

**Comment by sebawita** [comment]
hi @alexander171294,

sorry for the late reply. It was my mistake in the schematic, that added {N} paths to `tsconfig.json`.

A quick fix is to update `tsconfig.json` to:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

That should do the trick.

I am currently in the process of updating the schematics. Tomorrow the `ng new` schematic should be working correctly.
