### ISSUE TITLE
After ng add @nativescript/schematics, Angular web-project structure/code changed and dont work with ng serve -o

### ISSUE THREAD

**Issue by offline-pixel** [NativeScript/nativescript-schematics#287]
I am new to nativescript but an experienced developer. I have created an angular 9 workspace project and contain some projects and libraries with architecture as:-

```
projects 
   -- library 1
   -- library 2
   -- project 1
   -- project 2
src
   -- app
   -- index.html
```
I was migrating my project to nativescript and followed this [link](https://docs.nativescript.org/angular/code-sharing/migrating-a-web-project#migrating-existing-angular-web-projects). After,

`ng add @nativescript/schematics`
when i do,
`ng serve -o`

1. My project only show the content which is placed in `app.component.html` like some divs only.
2. However, I have also defined my `<router-outlet></router-outlet>` in `app.component.html` but this is not working. As of surprise, while compiling and browsing not showing/throwing any errors/warnings.
3. Each component has its own routing and module. Used lazy-load in `app.module.ts`

Apart from this, i created a small dummy project with the same structure but still no luck and i dont want to proceed if this will still persist. Have anyone came across this situation???

**package.json**
```
"dependencies": {
    "@nativescript/angular": "~9.0.0",
    "@nativescript/core": "~6.5.5",
    "@nativescript/theme": "~2.2.1",
    "reflect-metadata": "~0.1.12",
    "tslib": "^1.10.0",
    "@angular/animations": "~9.1.11",
    "@angular/common": "~9.1.11",
    "@angular/compiler": "~9.1.11",
    "@angular/core": "~9.1.11",
    "@angular/forms": "~9.1.11",
    "@angular/platform-browser": "~9.1.11",
    "@angular/platform-browser-dynamic": "~9.1.11",
    "@angular/router": "~9.1.11",
    "@nativescript/schematics": "^9.0.0"
    "rxjs": "~6.5.4",
    "zone.js": "~0.10.2"
  }
```

Still waiting for the answers on this [link](https://stackoverflow.com/questions/62985203/after-ng-add-nativescript-schematics-angular-web-project-shows-html-data-defin) from other helpful open-source community users too :)

**Comment by NathanWalker** [comment]
Fixed in latest release, please [see here for instructions of use](https://github.com/NativeScript/nativescript-schematics/pull/286#issuecomment-666116443).
