### ISSUE TITLE
Can't use Angular CLI with fresh nativescript installation

### ISSUE THREAD

**Issue by avif** [NativeScript/nativescript-schematics#311]
**Environment**
OS: Ubuntu 20.10 (Groovy Gorilla), 5.8.0-36-generic
node: 14.10.0
nativescript: 7.1.2
package.json: see repo [here](https://github.com/avif/native-test)

**Describe the bug**
I followed the guide to install the Angular CLI here [angular-cli](https://docs.nativescript.org/angular/tooling/angular-cli) with a fresh nativescript installation and could not get the Angualr CLI to work, I also could not successfully downgrade the angular version to get it to work.
On a side note, I also tried downloading the artifact from the playground but it had completely different versions and output js files laying around.

**To Reproduce**
```bash
npm i -g nativescript # nativescript@7.1.2
tns create native-test --ng
cd native-test
npm i -D @angular/cli # @angular/cli@11.1.2
npm i -D @nativescript/schematics # @nativescript/schematics@11.0.0
npx ng generate component test
An unhandled exception occurred: Cannot find module '@schematics/angular/utility/config'
Require stack:
- /home/test/Projects/native-test/node_modules/@nativescript/schematics/src/angular-project-parser.js
- /home/test/Projects/native-test/node_modules/@nativescript/schematics/src/generate/component/index.js
- /home/test/Projects/native-test/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/test/Projects/native-test/node_modules/@angular-devkit/schematics/tools/index.js
- /home/test/Projects/native-test/node_modules/@angular/cli/utilities/json-schema.js
- /home/test/Projects/native-test/node_modules/@angular/cli/models/command-runner.js
- /home/test/Projects/native-test/node_modules/@angular/cli/lib/cli/index.js
- /home/test/Projects/native-test/node_modules/@angular/cli/lib/init.js
- /home/test/Projects/native-test/node_modules/@angular/cli/bin/ng
See "/tmp/ng-iQvXCz/angular-errors.log" for further details.
```

**Expected behavior**
A new angular component is created and linked to main module.

**Sample project**
[native-test](https://github.com/avif/native-test)

**Additional context**
I looked at `@nativescript/schematics/src/angular-project-parser.js` and it seems to fail because of changes upstream that moved `getWorkspace` from `@schematics/angular/utility/config` to `@schematics/angular/utility/workspace`, tried to change that and got this error `Cannot read property 'hello-world' of undefined` which suggests it didn't find the workspace.

**Comment by plackowski** [comment]
Same problem here, how to fix it?

**Comment by Bezlepkin** [comment]
Hey! I have some problem! Has anyone solved this problem?

**Comment by Bezlepkin** [comment]
I install npm i @schematics/angular@11.0.1 (11.0.1) it's version of Angular in my project.
it worked for me!

**Comment by avif** [comment]
@Bezlepkin Didn't help..
I tried this:
```
npm i -D @schematics/angular@11.0.0 #(11.0.0) it's version of Angular in my project
npx ng generate component test

Option "entryComponent" is deprecated: Since version 9.0.0 with Ivy, entryComponents is no longer necessary.
Could not find an NgModule. Use the skip-import option to skip importing in NgModule.
```
And with latest version:
```
npm i -D @schematics/angular # 11.2.0
npx ng generate component test

An unhandled exception occurred: Cannot find module '@schematics/angular/utility/config'
Require stack:
- /home/test/Projects/native-test/node_modules/@nativescript/schematics/src/angular-project-parser.js
- /home/test/Projects/native-test/node_modules/@nativescript/schematics/src/generate/component/index.js
- /home/test/Projects/native-test/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/test/Projects/native-test/node_modules/@angular-devkit/schematics/tools/index.js
- /home/test/Projects/native-test/node_modules/@angular/cli/utilities/json-schema.js
- /home/test/Projects/native-test/node_modules/@angular/cli/models/command-runner.js
- /home/test/Projects/native-test/node_modules/@angular/cli/lib/cli/index.js
- /home/test/Projects/native-test/node_modules/@angular/cli/lib/init.js
- /home/test/Projects/native-test/node_modules/@angular/cli/bin/ng
See "/tmp/ng-xr1RzJ/angular-errors.log" for further details.
```

**Comment by JamesVal** [comment]
You have to use `angular-cli v10.2.x` which has the `config.ts` that the Nativescript CLI is looking for.  This will also mean you will have to install a compatible version of Angular, Typescript, and NodeJS for this all to work.  Here's a matrix of version compatibilities:

https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3

**Comment by lambourn** [comment]
As @avif  mentioned, the location of the `getWorkspace` was refactored:

> I looked at `@nativescript/schematics/src/angular-project-parser.js` and it seems to fail because of changes upstream that moved `getWorkspace` from `@schematics/angular/utility/config` to `@schematics/angular/utility/workspace`, tried to change that and got this error `Cannot read property 'hello-world' of undefined` which suggests it didn't find the workspace.

also, `getWorkspace` is now `async` so when calling, it has to be `await`ed.
