### ISSUE TITLE
Cannot find module '@schematics/angular/utility/config'

### ISSUE THREAD

**Issue by Guervyl** [NativeScript/nativescript-schematics#312]
**Environment**
Provide the content of the `package.json` file in the project:
`{
  "name": "@nativescript/template-hello-world-ng",
  "main": "main.js",
  "version": "7.0.9",
  "author": "NativeScript Team <oss@nativescript.org>",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "keywords": [
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "template"
  ],
  "repository": "<fill-your-repository-here>",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "dependencies": {
    "@angular/animations": "~11.0.0",
    "@angular/common": "~11.0.0",
    "@angular/compiler": "~11.0.0",
    "@angular/core": "~11.0.0",
    "@angular/forms": "~11.0.0",
    "@angular/platform-browser": "~11.0.0",
    "@angular/platform-browser-dynamic": "~11.0.0",
    "@angular/router": "~11.0.0",
    "@nativescript/angular": "~11.0.0",
    "@nativescript/core": "~7.1.0",
    "@nativescript/theme": "~3.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "zone.js": "~0.11.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.0.0",
    "@nativescript/android": "7.0.1",
    "@nativescript/schematics": "^11.0.0",
    "@nativescript/types": "~7.0.0",
    "@nativescript/webpack": "~4.0.0",
    "@ngtools/webpack": "~11.0.0",
    "@schematics/angular": "^11.1.4",
    "tslint": "^6.1.3",
    "typescript": "~4.0.0"
  },
  "private": "true",
  "readme": "NativeScript Application"
}
`

**Describe the bug**
I have run: `npm i -D @nativescript/schematics @schematics/angular tslint` in the project folder.
The when I try to `ng g c hello` I got:

```
An unhandled exception occurred: Cannot find module '@schematics/angular/utility/config'
Require stack:
- C:\wamp64\www\tns-tuto-new\node_modules\@nativescript\schematics\src\angular-project-parser.js
- C:\wamp64\www\tns-tuto-new\node_modules\@nativescript\schematics\src\generate\component\index.js
- C:\Users\guerb\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\guerb\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\guerb\AppData\Roaming\npm\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\guerb\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js
- C:\Users\guerb\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\guerb\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\guerb\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
See "C:\Users\guerb\AppData\Local\Temp\ng-hgrizI\angular-errors.log" for further details.
```
**Expected behavior**
I expected to automtically create a component.

**Comment by Bezlepkin** [comment]
I install npm i @schematics/angular@11.0.1 (11.0.1) it's version of Angular in my project.
it worked for me!

**Comment by Guervyl** [comment]
I don't know what is going on. Can you try with the package.json I print above? Because I install the version you use `npm i @schematics/angular@11.0.1` and it returns this:
```
An unhandled exception occurred: Cannot find module '@schematics/angular/utility/parse-name'
Require stack:
- C:\Users\guerb\AppData\Roaming\npm\node_modules\@nativescript\schematics\src\generate\component\index.js
- C:\Users\guerb\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\guerb\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\guerb\AppData\Roaming\npm\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\guerb\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js
- C:\Users\guerb\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\guerb\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\guerb\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
```

**Comment by Bezlepkin** [comment]
> An unhandled exception occurred: Cannot find module '@schematics/angular/utility/parse-name'

Did you make this step?

`npm i --save-dev @angular/cli
npm i --save-dev @nativescript/schematics
`

**Comment by Guervyl** [comment]
With `npm i --save-dev @nativescript/schematics` I don't get any `Cannot find module ...` anymore.
But now I got 
```
Option "entryComponent" is deprecated: Since version 9.0.0 with Ivy, entryComponents is no longer necessary.
Could not find an NgModule. Use the skip-import option to skip importing in NgModule.
```
This is the default project generated by the tns command. The `app.module.ts` exists in the folder `src\app`  . With `ng g c hello --skip-import` it generates the files in `src\app` with an error `Failed to generate remapped imports! Please see: https://docs.nativescript.org/angular/code-sharing/intro#remapped-imports` and a warning `Option "entryComponent" is deprecated: Since version 9.0.0 with Ivy, entryComponents is no longer necessary.`. I don't have any "entryComponent" in my `NgModule`.

**Comment by Bezlepkin** [comment]
> With `npm i --save-dev @nativescript/schematics` I don't get any `Cannot find module ...` anymore.
> But now I got
> 
> ```
> Option "entryComponent" is deprecated: Since version 9.0.0 with Ivy, entryComponents is no longer necessary.
> Could not find an NgModule. Use the skip-import option to skip importing in NgModule.
> ```
> 
> This is the default project generated by the tns command. The `app.module.ts` exists in the folder `src\app` . With `ng g c hello --skip-import` it generates the files in `src\app` with an error `Failed to generate remapped imports! Please see: https://docs.nativescript.org/angular/code-sharing/intro#remapped-imports` and a warning `Option "entryComponent" is deprecated: Since version 9.0.0 with Ivy, entryComponents is no longer necessary.`. I don't have any "entryComponent" in my `NgModule`.

Error or Warning? I have same... But, generating is work! Import no.
![2021-02-18_10-19-13](https://user-images.githubusercontent.com/10475699/108319661-c826f800-71d2-11eb-990f-9eaf994ad642.png)

**Comment by Guervyl** [comment]
In that case, generate components `ng g c` should be declared manually in the `app.module.ts`? Because the reason I use the command to generate components is because I don't want to open the `AppModule` everytime.

**Comment by Bezlepkin** [comment]
> In that case, generate components `ng g c` should be declared manually in the `app.module.ts`? Because the reason I use the command to generate components is because I don't want to open the `AppModule` everytime.

Unfortunately I didn't find a solution:( Yes, you have to manually add components to modules...

The authors are silent...

**Comment by Guervyl** [comment]
Too bad. But thanks for your help.
