### ISSUE TITLE
Is this project deprecated?

### ISSUE THREAD

**Issue by mohammadrafigh** [NativeScript/nativescript-schematics#323]
It seems there is no schematics integration with NativeScript 8. In the docs it's mentioned to use Nx and Xplat. Is this project deprecated and should be replaced by Nx, Xplat?? Isn't there any guide for that? it seems to be a huge work!!!

**Comment by kriefsacha** [comment]
Did you got news from this @mohammadrafigh ?

**Comment by mohammadrafigh** [comment]
@kriefsacha yeah it seems the project is deprecated and they encourage to use Xplat and NX instead. take a look at [here](https://docs.nativescript.org/code-sharing/#nrwl-nx-devtools-with-nativescript-nx). I migrated my project to xplat, The project now includes a lot of boilerplate files generated by xplat but generally I'm happy with the migration. IMO xplat is the way to go but it needs a lot of improvements and docs.
