### ISSUE TITLE
It would be great to integrate with @ngrx/schematics

### ISSUE THREAD

**Issue by liuwei108** [NativeScript/nativescript-schematics#36]
the ng generate command in
https://github.com/ngrx/platform/tree/master/docs/schematics
can not generate correct ngrx files in nativescript project.

**Comment by sebawita** [comment]
Hi @liuwei108,
Can you describe a bit more:

 * what you are trying to do?
 * what errors are you getting?
 * what commands are you using?
 * how to reproduce your issues?
