### ISSUE TITLE
Cannot find module "tns-core-modules/application"

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-schematics#37]
_From @Kamieniu on July 13, 2018 18:23_

MacOS HighSierra 10.13.3
Node 9.6.1
NPM 6.1.0

### Tell us about the problem
I try to run `npm run ios` on my Angular + NativeScript project. Project is CLEAN! 
I used `ng new app` and `ng add @nativescript/schematics`

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) `4.1.2`
- Cross-platform modules: (check the 'version' attribute in the 
`node_modules/tns-core-modules/package.json` file in your project) `4.1.0`
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the 
`package.json` file of your project) tns-ios `4.1.1`
 
- Plugin(s): (look for the version number in the `package.json` file of your
project) `0.0.0`

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

`ng new angular-app`
`cd angular-app`
`ng add @nativescript/schematics`
`npm run ios`

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

There are plenty of errors.

This one occured at the end.

`JavaScript error:
file:///app/vendor.js:55195:167: JS ERROR Error: Cannot find module "tns-core-modules/application"`

.. but this kind of error occured multiple times with defferent 'Can't resolve' file.

`ERROR in ../node_modules/tns-core-modules/bundle-entry-points.js
Module not found: Error: Can't resolve 'ui/segmented-bar' in '/Users/franciszekstodulski/Develop/native-app/node_modules/tns-core-modules'
 @ ../node_modules/tns-core-modules/bundle-entry-points.js 29:67-94
 @ ./main.ns.ts`

_Copied from original issue: NativeScript/NativeScript#6068_

**Comment by tsonevn** [comment]
_From @erkanarslan on July 15, 2018 21:34_

How do you try to import application package?

**Comment by tsonevn** [comment]
HI @erkanarslan,
Can you try whether you will have the same issue while using `@angular/cli` version  `6.1.0-beta.0` ?

**Comment by neerajjsr** [comment]
Hi @sebawita, I am also getting same exception when trying to setup a Hello World angular app with Nativescript capability. 

Followed same below steps - 
. ng new angular-app
. cd angular-app
. ng add @nativescript/schematics
. npm run ios

npm version - 6.1.0 
node - v8.10.0
tns version - 4.1.2

Got the same error file:///app/vendor.js:55195:167: JS ERROR Error: Cannot find module "tns-core-modules/application"

Afterward added @angular/cli@6.1.0-beta.0 , still getting same above error. 

Really appreciate if you can share some sample boiler plate working project with angular 6.x

**Comment by langan** [comment]
I found that running the schematics when you create the app stopped this error

```ng new --c=@nativescript/schematics --name=angular-project --shared
tns run ios --bundle```

**Comment by sebawita** [comment]
@neerajjsr we've just updated the schematics to `0.2.1`. Can you check if it works with the latest?

also, please make sure to use `@angular/cli@6.1.0-rc.3` in your Angular project, before you call `ng add`
