### ISSUE TITLE
Web + Mobile Code Sharing project not working

### ISSUE THREAD

**Issue by mhinostroza** [NativeScript/nativescript-schematics#38]
Mac os high sierra 10.13.6
NodeJS v10.4.1

with comand: ng new --collection=@nativescript/schematics --name=my-shared-app --shared

Angular CLI: 6.1.0-beta.0
Node: 10.4.1
OS: darwin x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.0-beta.0
@angular-devkit/build-angular     0.7.0-beta.0
@angular-devkit/build-optimizer   0.7.0-beta.0
@angular-devkit/core              0.7.0-beta.0
@angular-devkit/schematics        0.7.0-beta.0
@angular/cli                      6.1.0-beta.0
@ngtools/webpack                  6.1.0-beta.0
@schematics/angular               0.7.0-beta.0
@schematics/update                0.7.0-beta.0
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.6.0

Error when: tns run ios

platforms/ios/build/emulator/myappcollection.app/app/tns_modules/rxjs/observable/GenerateObservable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/observable/GenerateObservable'.
platforms/ios/build/emulator/myappcollection.app/app/tns_modules/rxjs/observable/IfObservable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/observable/IfObservable'.
platforms/ios/build/emulator/myappcollection.app/app/tns_modules/rxjs/observable/IntervalObservable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/observable/IntervalObservable'.
platforms/ios/build/emulator/myappcollection.app/app/tns_modules/rxjs/observable/IteratorObservable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/observable/IteratorObservable'.
platforms/ios/build/emulator/myappcollection.app/app/tns_modules/rxjs/observable/NeverObservable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/observable/NeverObservable'.
platforms/ios/build/emulator/myappcollection.app/app/tns_modules/rxjs/observable/PairsObservable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/observable/PairsObservable'.
platforms/ios/build/emulator/myappcollection.app/app/tns_modules/rxjs/observable/PromiseObservable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/observable/PromiseObservable'.
platforms/ios/build/emulator/myappcollection.app/app/tns_modules/rxjs/observable/RangeObservable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/observable/RangeObservable'.
platforms/ios/build/emulator/myappcollection.app/app/tns_modules/rxjs/observable/ScalarObservable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/observable/ScalarObservable'.
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x1049ba649 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x1049ed860 -[TNSRuntime executeModule:referredBy:]
3   0x104495261 main
4   0x10a351d81 start
5   0x1
JavaScript stack trace:
1   @[native code]
2   promiseReactionJob@[native code]
JavaScript error:
[native code]: JS ERROR Error: Could not find module './'. Computed path '/Users/michelhinostrozaparra/Library/Developer/CoreSimulator/Devices/76CDD6F5-6900-471A-B818-40CE8A69F570/data/Containers/Bundle/Application/3062415D-0621-4CAD-A8BB-71E9F92C0E82/myappcollection.app/app'.

any suggestions?

**Comment by sebawita** [comment]
@jdaf2008 @mhinostroza Yes, you need to use `--bundle` to build NativeScript apps.
This is because we are using webpack for {N} builds to pick `.tns` files instead of the files without `.tns` (which should be used for the web projects).

Without webpack it would be hard for us to distinguish between files like:
`app.component.html` and `app.component.tns.html`
