### ISSUE TITLE
Cannot find name 'module'. in Web + mobile code sharing new collection

### ISSUE THREAD

**Issue by jdaf2008** [NativeScript/nativescript-schematics#40]
Linux Ubuntu 18.04 LTS
NPM version: 6.2.0
node version: 8.11.3

## Tell us about the problem

I used `ng new -c=@nativescript/schematics --name=simulator --shared`
I tried to run `ng serve` on my Angular + NativeScript project. and then I got:

`ERROR in src/app/app.component.ts(5,13): error TS2304: Cannot find name 'module'.
src/app/barcelona/player-detail/player-detail.component.ts(9,13): error TS2304: Cannot find name 'module'.
src/app/barcelona/players/players.component.ts(8,13): error TS2304: Cannot find name 'module'.
`
## Which platform(s) does your issue occur on?
web

### package.json

{
  "name": "simulator",
  "nativescript": {
    "id": "org.nativescript.simulator"
  },
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "core-js": "^2.5.4",
    "nativescript-angular": "^6.0.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^6.0.0",
    "tns-core-modules": "~4.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.7.0-beta.0",
    "@angular/cli": "^6.1.0-rc.2",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.14.0",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "2.7.2"
  }
}

## Please tell us how to recreate the issue in as much detail as possible

I created a new code sharing project following the webinar NS 4.1 steps

`npm i -g @angular/cli@6.1.0-beta.0` 
`npm i -g @nativescript/schematics`
`ng new -c@nativescript/schematics --name=simulator --shared`
`cd simulator/`
`npm i`
`ng serve -o`

I got this error:

`ERROR in src/app/app.component.ts(5,13): error TS2304: Cannot find name 'module'.
src/app/barcelona/player-detail/player-detail.component.ts(9,13): error TS2304: Cannot find name 'module'.
src/app/barcelona/players/players.component.ts(8,13): error TS2304: Cannot find name 'module'.
`

_**I have proved with either `@angular/cli@6.1.0-beta.0` or `@angular/cli@6.1.0-rc.2`**_ 

Any suggestions?

**Comment by sebawita** [comment]
Hi @jdaf2008,
with some of the latest updates to `nativescript-dev-webpack` we no longer need `moduleId` for the components to work.

I've updated `@nativescript/schematics`, so that `moduleId` is no longer appended to code sharing projects. Can you please update `@nativescript/schematics` and try again?

**Comment by jdaf2008** [comment]
Thanks, @sebawita, It works for me
